### ISSUE TITLE
de-flicker

### ISSUE THREAD

**Issue by b4zz4** [jamriska/ebsynth#15]
Hi.
Is there a way to create "de-flicker" from the command line?

https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/mographsocial/media_attachments/files/000/296/915/original/3dc88fa4b22b735b.mp4

**Comment by b4zz4** [comment]
This fix  with an image of flow

**Comment by tharunmohandoss96** [comment]
Hi @b4zz4 , could you let me know how the issue was resolved. Where can I find the de-flicker option for command line?

**Comment by b4zz4** [comment]
It's not that easy, you have to create extra guides for the frames, so they know what to do when the image didn't give you references.

**Comment by Bez22** [comment]
Hey @b4zz4 were there any patterns in where the extra guide frames needed to be? I was planning to use the deflicker and dirt removal nodes in Davinci Resolve to remove flickering but it would be great if I could fix it before leaving ebsynth.

**Comment by b4zz4** [comment]
@Bez22 These are my little guides as ebsynth use:

https://4232.cf/?s=ebsynth

**Comment by Bez22** [comment]
I can't tell you how much I appreciate this! It's going to be such a game-changer as I begin to get the hang of ebsynth. Thanks
