### ISSUE TITLE
Problems when compiling for ubuntu 18.04

### ISSUE THREAD

**Issue by Sam2much96** [jamriska/ebsynth#17]
I run the build-linux-cpu_only.sh script, and the terminal just remains blank. I've tried using the windows version, but my windows PC is so slow. Please help fix this. I really need to start testing with ebsynth asap.

**Comment by Sam2much96** [comment]
On further inspection, the source code doesn't have a .make file or a .config file for building in Ubuntu terminal. Please create a .make file for Linux builds

**Comment by Touitoui** [comment]
The .sh scripts are g++ commands without verbose, the terminal remain blank because it's compiling.
Just wait a little and the executable will be in the bin folder.

**Comment by Sam2much96** [comment]
You're a genius. Thank you. Forgive a Linux noob like myself. I suggest maybe an addition to the code? A for loop with an asterix that shows build percentage. It'll really help.

**Comment by meet1919** [comment]
@Touitoui  hey, what to do after the bin folder is populated? I tried adding it to the path but when using command `ebsynth -style <style.png> -guide <source.png> <target.png> -output <output.png>` error comes: `ebsynth : The term 'ebsynth' is not recognized as the name of a cmdlet, function, script file, or operable program`.  I am using windows and compiled with `build-win64-cpu_only.bat`
