### ISSUE TITLE
Code for generate G_seg?

### ISSUE THREAD

**Issue by dypromise** [jamriska/ebsynth#3]
Is there any implemented G_seg generator code?

**Comment by sonej** [comment]
I would also like to know how one would go about generate this.

**Comment by OndrejTexler** [comment]
Not a code, but you can find some more information in the corresponding paper: [Fiser2017](http://dcgi.fel.cvut.cz/home/sykorad/Fiser17-SIG.pdf). In case you are interested in faces, visit also [FaceStyle Homepage](http://dcgi.fel.cvut.cz/home/sykorad/facestyle.html).

**Comment by dypromise** [comment]
> Not a code, but you can find some more information in the corresponding paper: [Fiser2017](http://dcgi.fel.cvut.cz/home/sykorad/Fiser17-SIG.pdf). In case you are interested in faces, visit also [FaceStyle Homepage](http://dcgi.fel.cvut.cz/home/sykorad/facestyle.html).
Thanks for your reply. I know this paper and the step to generate Gseg, but I haven't implement it yet, I mean if anyone have a implementation, i can use it directly, without waste of my time.
