### ISSUE TITLE
Compiling ebsynth_win64 for cuda?

### ISSUE THREAD

**Issue by Trentonom0r3** [jamriska/ebsynth#37]
I've tried changing the compute_30 field, which lets it compile, but the gpu output returns a black image, whereas the cpu output returns the output as expected. 

Anyone have any ideas?

**Comment by Trentonom0r3** [comment]
-arch compute_86 does not work, but -arch=sm_86 does!

**Comment by monstari** [comment]
Hello, I have both tried compute_89 and sm_89 for my enviroment but got this error everytime: "cudadevrt.lib" not found. Anyone had this or fixed this issue?
