### ISSUE TITLE
Code to generate diffusion curves

### ISSUE THREAD

**Issue by vikasTmz** [jamriska/ebsynth#8]
Could you provide the code to generate diffusion curves and render it onto an image.

As far as I've looked, the authors of the original paper haven't released their source code.

**Comment by OndrejTexler** [comment]
Hello. I would not bother with diffusion curves that much. Just try to "fake it" somehow. Maybe, try to do the segmentation and blur or blend individual segments together, somehow - it does not need to be perfect.
